; PlatformIO Project Configuration File
; Pigeon - Encrypted Mesh Networking Messenger
; Hardware: Seeed XIAO ESP32S3 + Wio-SX1262 LoRa Shield

[env]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
lib_deps =
    jgromes/RadioLib@^7.1.2

[env:transmitter]
build_src_filter = +<../src/tx.cpp>

[env:receiver]
build_src_filter = +<../src/rx.cpp>

[env:mesh]
build_src_filter = +<../src/mesh.cpp>

[env:pigeon]
build_src_filter = +<../src/pigeon.cpp>
board_build.partitions = huge_app.csv
