; PlatformIO Project Configuration File
; Pigeon - Encrypted Mesh Networking Messenger
; Hardware: Seeed XIAO ESP32S3 + Wio-SX1262 LoRa Shield

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
lib_deps =
    jgromes/RadioLib@^7.1.2
